apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: jinchenhu/posts:latest
          
---
apiVersion: v1
kind: Service
metadata:
  name: blog-posts-service
spec:
  selector:
    app: posts
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: posts
